const latarBelakang = {
	paragraphone:
		'Kami adalah bagian dari PSB (Persatuan Skateboarders Bali), Kami adalah organisasi resmi yang mewadahi komunitas skateboard di daerah Bangli (PSB Bangli) berada dibawah naungan PSB yang mewadahi seluruh komunitas skateboard di Bali. PSB Bangli dibentuk dan dibangun oleh orang-orang yang memiliki passion dan keinginan tinggi dalam mengembangkan extreme sport di daerah Bangli khususnya skateboard agar potensi dari anak-anak muda yang menggemari skateboard bisa tersalurkan lebih baik dan terarah, sehingga potensi yang ada dapat dikembangkan menjadi prestasi yang kelak dapat membanggakan nama daerah, bangsa serta negara kedepannya dibidang olahraga ini. ',
	paragraphtwo:
		'Dengan suksesnya event Bupati Cup Competition I tahun 2022 lalu, dengan ini kami ingin melanjutkan event positif ini menjadi event tahunan dan selalu ditunggu- tunggu oleh seluruh komunitas skateboard di Bali pada umumnya. Dengan adanya event berkelanjutan, maka besar harapan kami dari pengurus daerah untuk dapat menumbuh kembangkan olahraga skateboard ini menjadi olahraga yang dapat dijadikan alternatif baru bagi generasi muda Bangli dan Bali dalam melaksanakan aktivitas kreatif mereka ke arah prestasi yang dimana olahraga skateboard sudah diakui oleh dunia sebagai olahraga prestasi yang sudah masuk di kompetisi resmi baik dari Extreme Games, SEA Games, ASIAN Games dan Olympiade. Support yang telah diberikan terhadap kegiatan kami merupakan semangat yang mendorong kami untuk tetap aktif dan berusaha memberikan yang terbaik untuk membangun potensi bibit-bibit atlit skateboard yang berprestasi dan mengharumkan serta membawa nama Kabupaten Bangli di kancah event Local, National dan bahkan International sebagai target terbesar yang ingin kami capai kedepannya nanti.',
};
const pendahuluan = {
	paragraphone:
		'BANGLI skateboarding adalah sekumpulan pemuda Bangli yang membentuk sebuah organisasi skateboard pada tahun 2003 dan baru berkembang pada tahun 2005 yang dikembangkan oleh anak muda di bangli. Salah satu skater yang memperkenalkan skateboard di Bangli kepada anak muda bangli, dan sampai sekarang hingga banyak peminatnya. Seiring berjalannya waktu orang-orang yang gemar bermain skateboard di area Lapangan Kapten Mudita Bangli, dan pada tahun 2018 kami resmi menjadi bagian dari organisasi Persatuan Skateboarders Bali (PSB Bangli), dan pada tahun 2021 telah dibangun skatepark di Lapangan Kapten mudita Bangli, yang bernama (BANGLI SKATEPARK). ',
	paragraphtwo:
		'Dengan diadakannya kegiatan ini di harapkan anak-anak muda atau remaja zaman sekarang dapat menyalurkan apresiasinya kedalam sebuah bentuk kegiatan yang positif. Selain itu dengan diadakannya kompetisi skateboarding di Bangli ini bertujuan untuk meningkatkan minat anak muda bermain skateboard, dan juga sebagai media promosi untuk memperkenalkan BANGLI SKATEPARK.',
};
export { latarBelakang, pendahuluan };
